name: Build APK Tu Tien
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cai dat phan mem can thiet
        run: |
          sudo apt-get update
          sudo apt-get install -y zip

      - name: Dong goi file .love
        run: |
          zip -9 -r game.love . -x ".github/*"

      - name: Tai cong cu dong goi tu dong
        run: |
          wget https://github.com/love2d/love-android/releases/download/11.5/love-11.5-android-embed.apk -O love-base.apk

      - name: Tron file game vao APK
        run: |
          cp love-base.apk game-chua-ky.apk
          zip -g game-chua-ky.apk game.love

      - name: Luu file APK san pham
        uses: actions/upload-artifact@v4
        with:
          name: GameTuTien-APK
          path: game-chua-ky.apk
