name: Build APK gugugaga
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Dong goi LOVE Android
        uses: adityashares/love-actions@v1.1.1
        with:
          platform: android
